### ISSUE TITLE
No license information.

### ISSUE THREAD

**Issue by apteryks** [WuBingzheng/libwuya#2]
Please provide a LICENSE file at the root of the repository clearly indicating which license this is distributed under.

Thanks :-)

**Comment by WuBingzheng** [comment]
I have not add the LICENSE information because I think this library is in process and not ready to publish. The code should be OK but the APIs may change.
I am going to add more documents (e.g. README, api) when I think it's ready. 

It will be GPLv2 if you want to know now.

Thanks for your attention

**Comment by apteryks** [comment]
Hello Wu, and thanks for the prompt feedback and clarification!

My 2 cents: the code *is* already published :-).  And it's used in the libleak tool.  It'd be nice if the LICENSE file was already present for clarity.  I've added this as a package in GNU Guix already (we try to unbundle libraries when possible; something I did for libleak).

Thanks!

**Comment by WuBingzheng** [comment]
LICENSE file is done :)

**Comment by apteryks** [comment]
Thanks! Closing :-).
